### ISSUE TITLE
Correct handling of "more" replies

### ISSUE THREAD

**Issue by jmarianer** [phallstrom/scorm_engine#18]
The examples in the documentation show "more" in the response to be a URL, but it shouldn't be treated as such. Rather, it should be passed in opaquely as the "more" parameter in the next request.

Note that I haven't tested this either way; I was simply reviewing some code and docs and noticed that they didn't match.

**Comment by phallstrom** [comment]
We're good. Until V2 api comes out.

> What you are doing is fine. That note about 'may change without notice' is talking about the value of the 'more' url parameter that you see in that url you posted, not the value of the 'more' property returned in the results. 
> 
> It's a bit confusing, I admit. We're actually changing it in version 2 of our API that will come out with 2018.1 Engine (v1 of the API will still be there, though). In the new API we will be returning the more token (not the full url) in the response, and then you'd turn around and call the endpoint again passing in that token.
> 
> However, in v1 of the API that you are using, you either do what you're doing now (use the more url from the response directly in a second request), or you could parse that 'more' url to pull off only the 'more' token and then use that in a call to the API. That option might make more sense if you were using the client library methods to make the calls.
>
